/**
 * Mapbox {@link feature.place_name} tails and context country names we treat as reliable.
 * Used only to avoid inventing a country from an arbitrary last comma segment (e.g. a street).
 */

function normKey(s: string): string {
  return s
    .trim()
    .toLowerCase()
    .replace(/\.+/g, "")
    .replace(/\s+/g, " ")
}

const KNOWN_MAPBOX_COUNTRY_KEYS = new Set<string>(
  [
    "afghanistan",
    "albania",
    "algeria",
    "andorra",
    "angola",
    "argentina",
    "armenia",
    "australia",
    "austria",
    "azerbaijan",
    "bahrain",
    "bangladesh",
    "belarus",
    "belgium",
    "belize",
    "bolivia",
    "bosnia and herzegovina",
    "botswana",
    "brazil",
    "brunei",
    "bulgaria",
    "cambodia",
    "canada",
    "chile",
    "china",
    "colombia",
    "costa rica",
    "croatia",
    "cyprus",
    "czech republic",
    "czechia",
    "denmark",
    "dominican republic",
    "ecuador",
    "egypt",
    "el salvador",
    "estonia",
    "ethiopia",
    "fiji",
    "finland",
    "france",
    "georgia",
    "germany",
    "ghana",
    "greece",
    "guatemala",
    "honduras",
    "hong kong",
    "hungary",
    "iceland",
    "india",
    "indonesia",
    "iran",
    "iraq",
    "ireland",
    "israel",
    "italy",
    "ivory coast",
    "cote divoire",
    "jamaica",
    "japan",
    "jordan",
    "kazakhstan",
    "kenya",
    "kosovo",
    "kuwait",
    "latvia",
    "lebanon",
    "libya",
    "liechtenstein",
    "lithuania",
    "luxembourg",
    "malaysia",
    "maldives",
    "malta",
    "mauritius",
    "mexico",
    "moldova",
    "monaco",
    "mongolia",
    "montenegro",
    "morocco",
    "myanmar",
    "nepal",
    "netherlands",
    "new zealand",
    "nicaragua",
    "nigeria",
    "north macedonia",
    "macedonia",
    "norway",
    "oman",
    "pakistan",
    "palestine",
    "panama",
    "paraguay",
    "peru",
    "philippines",
    "poland",
    "portugal",
    "puerto rico",
    "qatar",
    "romania",
    "russia",
    "saudi arabia",
    "senegal",
    "serbia",
    "singapore",
    "slovakia",
    "slovenia",
    "south africa",
    "south korea",
    "korea",
    "spain",
    "sri lanka",
    "sweden",
    "switzerland",
    "taiwan",
    "tanzania",
    "thailand",
    "tunisia",
    "turkey",
    "turkiye",
    "uganda",
    "ukraine",
    "united arab emirates",
    "uae",
    "united kingdom",
    "great britain",
    "uk",
    "england",
    "scotland",
    "wales",
    "northern ireland",
    "united states",
    "united states of america",
    "usa",
    "us",
    "uruguay",
    "uzbekistan",
    "venezuela",
    "vietnam",
    "viet nam",
    "zambia",
    "zimbabwe",
    // ISO-style short names Mapbox sometimes uses in tails
    "au",
    "nz",
    "uk",
    "us",
    "gb",
    "ie",
    "fr",
    "de",
    "es",
    "it",
    "pt",
    "nl",
    "be",
    "at",
    "ch",
    "se",
    "no",
    "dk",
    "fi",
    "pl",
    "cz",
    "gr",
    "jp",
    "kr",
    "cn",
    "in",
    "sg",
    "my",
    "th",
    "id",
    "ph",
    "vn",
    "mx",
    "br",
    "ar",
    "cl",
    "co",
    "za",
    "eg",
    "il",
    "tr",
    "ru",
    "ua",
    "hr",
    "hu",
    "ro",
    "is",
    "lu",
    "ca",
  ].map((s) => normKey(s)),
)

/**
 * True when {@param segment} is a plausible Mapbox country label (not a street or suburb).
 */
export function isKnownMapboxCountryName(segment: string): boolean {
  const t = segment?.trim()
  if (!t) return false
  const key = normKey(t)
  if (key.length < 2) return false
  // Numeric tails are postcodes, not countries
  if (/^\d{3,}$/.test(key.replace(/\s/g, ""))) return false
  return KNOWN_MAPBOX_COUNTRY_KEYS.has(key)
}

/**
 * Last comma segment of {@param placeName} only when it looks like a real country
 * (requires ≥2 segments so single-token queries do not become "country = street").
 */
export function mapboxCountryFromPlaceNameTailIfKnown(placeName: string | undefined | null): string | null {
  if (!placeName?.trim()) return null
  const parts = placeName.split(",").map((p) => p.trim()).filter(Boolean)
  if (parts.length < 2) return null
  const tail = parts[parts.length - 1]!
  if (!isKnownMapboxCountryName(tail)) return null
  return tail
}
