-- Seed 12 sample events across different categories and languages

INSERT INTO "Event" (
  id, title, description, categories, "startAt", "endAt", timezone,
  "venueName", address, city, country, lat, lng, "priceFree", "websiteUrl", languages,
  "imageUrls", "createdById", "searchText", "searchTextFolded", status, "createdAt", "updatedAt"
) VALUES
  -- Market events
  (
    'seed001',
    'Athens Farmers Market',
    'Fresh local produce, artisan goods, and traditional Greek products every Sunday morning.',
    ARRAY['market', 'food', 'outdoor'],
    NOW() + INTERVAL '3 days',
    NOW() + INTERVAL '3 days' + INTERVAL '4 hours',
    'Europe/Athens',
    'Plateia Avissinias',
    'Plateia Avissinias, Monastiraki, Athens, Greece',
    'Athens',
    'Greece',
    37.9755,
    23.7239,
    true,
    'https://example.com/athens-market',
    ARRAY['el', 'en'],
    ARRAY['/placeholder.svg?height=400&width=600'],
    'seed-user-001',
    'Athens Farmers Market Fresh local produce artisan goods traditional Greek products market food outdoor Athens Greece',
    'athens farmers market fresh local produce artisan goods traditional greek products market food outdoor athens greece',
    'PUBLISHED',
    NOW(),
    NOW()
  ),
  (
    'seed002',
    'Mercato di Porta Palazzo',
    'Il più grande mercato all''aperto d''Europa con prodotti freschi, abbigliamento e molto altro.',
    ARRAY['market', 'food', 'shopping'],
    NOW() + INTERVAL '1 day',
    NOW() + INTERVAL '1 day' + INTERVAL '6 hours',
    'Europe/Rome',
    'Porta Palazzo',
    'Piazza della Repubblica, Turin, Italy',
    'Turin',
    'Italy',
    45.0781,
    7.6838,
    true,
    NULL,
    ARRAY['it', 'en'],
    ARRAY['/placeholder.svg?height=400&width=600'],
    'seed-user-001',
    'Mercato di Porta Palazzo market food shopping Turin Italy',
    'mercato di porta palazzo market food shopping turin italy',
    'PUBLISHED',
    NOW(),
    NOW()
  ),
  -- Music & Festival events
  (
    'seed003',
    'Barcelona Jazz Festival',
    'International jazz artists performing across multiple venues in the Gothic Quarter.',
    ARRAY['music', 'festival', 'culture'],
    NOW() + INTERVAL '14 days',
    NOW() + INTERVAL '17 days',
    'Europe/Madrid',
    'Various Venues',
    'Gothic Quarter, Barcelona, Spain',
    'Barcelona',
    'Spain',
    41.3851,
    2.1734,
    false,
    'https://example.com/bcn-jazz',
    ARRAY['es', 'en', 'fr'],
    ARRAY['/placeholder.svg?height=400&width=600'],
    'seed-user-002',
    'Barcelona Jazz Festival music festival culture international artists Barcelona Spain',
    'barcelona jazz festival music festival culture international artists barcelona spain',
    'PUBLISHED',
    NOW(),
    NOW()
  ),
  (
    'seed004',
    'Fête de la Musique Paris',
    'Célébration annuelle de la musique avec des concerts gratuits dans toute la ville.',
    ARRAY['music', 'festival', 'free'],
    NOW() + INTERVAL '60 days',
    NOW() + INTERVAL '60 days' + INTERVAL '12 hours',
    'Europe/Paris',
    'Citywide',
    'Paris, France',
    'Paris',
    'France',
    48.8566,
    2.3522,
    true,
    'https://example.com/fete-musique',
    ARRAY['fr', 'en'],
    ARRAY['/placeholder.svg?height=400&width=600'],
    'seed-user-002',
    'Fête de la Musique Paris music festival free concerts Paris France',
    'fete de la musique paris music festival free concerts paris france',
    'PUBLISHED',
    NOW(),
    NOW()
  ),
  -- Cultural events
  (
    'seed005',
    'Πανηγύρι Αγίου Δημητρίου',
    'Παραδοσιακό πανηγύρι με ζωντανή μουσική, χορό και τοπικά εδέσματα.',
    ARRAY['festival', 'culture', 'food', 'traditional'],
    NOW() + INTERVAL '21 days',
    NOW() + INTERVAL '21 days' + INTERVAL '8 hours',
    'Europe/Athens',
    'Πλατεία Αγίου Δημητρίου',
    'Thessaloniki, Greece',
    'Thessaloniki',
    'Greece',
    40.6401,
    22.9444,
    true,
    NULL,
    ARRAY['el'],
    ARRAY['/placeholder.svg?height=400&width=600'],
    'seed-user-003',
    'Πανηγύρι Αγίου Δημητρίου festival culture food traditional Greek Thessaloniki Greece',
    'πανηγυρι αγιου δημητριου festival culture food traditional greek thessaloniki greece',
    'PUBLISHED',
    NOW(),
    NOW()
  ),
  (
    'seed006',
    'Fiesta de San Fermín',
    'Celebración tradicional con encierros, música y eventos culturales en Pamplona.',
    ARRAY['festival', 'culture', 'traditional'],
    NOW() + INTERVAL '90 days',
    NOW() + INTERVAL '97 days',
    'Europe/Madrid',
    'Plaza del Castillo',
    'Pamplona, Navarra, Spain',
    'Pamplona',
    'Spain',
    42.8169,
    -1.6432,
    true,
    'https://example.com/san-fermin',
    ARRAY['es', 'en'],
    ARRAY['/placeholder.svg?height=400&width=600'],
    'seed-user-003',
    'Fiesta de San Fermín festival culture traditional Pamplona Spain',
    'fiesta de san fermin festival culture traditional pamplona spain',
    'PUBLISHED',
    NOW(),
    NOW()
  ),
  -- Art & Exhibition events
  (
    'seed007',
    'Contemporary Art Exhibition',
    'Showcase of emerging European artists exploring themes of identity and technology.',
    ARRAY['art', 'exhibition', 'culture'],
    NOW() + INTERVAL '7 days',
    NOW() + INTERVAL '37 days',
    'Europe/Rome',
    'Galleria Nazionale',
    'Viale delle Belle Arti, 131, Rome, Italy',
    'Rome',
    'Italy',
    41.9171,
    12.4913,
    false,
    'https://example.com/art-rome',
    ARRAY['it', 'en'],
    ARRAY['/placeholder.svg?height=400&width=600'],
    'seed-user-004',
    'Contemporary Art Exhibition art exhibition culture European artists Rome Italy',
    'contemporary art exhibition art exhibition culture european artists rome italy',
    'PUBLISHED',
    NOW(),
    NOW()
  ),
  (
    'seed008',
    'Street Art Festival Athens',
    'Urban art installations and live mural painting across the Psyrri neighborhood.',
    ARRAY['art', 'festival', 'outdoor', 'free'],
    NOW() + INTERVAL '10 days',
    NOW() + INTERVAL '12 days',
    'Europe/Athens',
    'Psyrri District',
    'Psyrri, Athens, Greece',
    'Athens',
    'Greece',
    37.9792,
    23.7244,
    true,
    NULL,
    ARRAY['el', 'en'],
    ARRAY['/placeholder.svg?height=400&width=600'],
    'seed-user-004',
    'Street Art Festival Athens art festival outdoor free urban installations Athens Greece',
    'street art festival athens art festival outdoor free urban installations athens greece',
    'PUBLISHED',
    NOW(),
    NOW()
  ),
  -- Food events
  (
    'seed009',
    'Salon du Chocolat',
    'Le plus grand événement dédié au chocolat avec des démonstrations et dégustations.',
    ARRAY['food', 'exhibition', 'workshop'],
    NOW() + INTERVAL '45 days',
    NOW() + INTERVAL '48 days',
    'Europe/Paris',
    'Porte de Versailles',
    'Paris Expo, Paris, France',
    'Paris',
    'France',
    48.8322,
    2.2866,
    false,
    'https://example.com/salon-chocolat',
    ARRAY['fr', 'en'],
    ARRAY['/placeholder.svg?height=400&width=600'],
    'seed-user-005',
    'Salon du Chocolat food exhibition workshop chocolate demonstrations Paris France',
    'salon du chocolat food exhibition workshop chocolate demonstrations paris france',
    'PUBLISHED',
    NOW(),
    NOW()
  ),
  (
    'seed010',
    'Tapas & Wine Tasting',
    'Evening of traditional Spanish tapas paired with regional wines from Rioja.',
    ARRAY['food', 'wine', 'culture'],
    NOW() + INTERVAL '5 days',
    NOW() + INTERVAL '5 days' + INTERVAL '3 hours',
    'Europe/Madrid',
    'Casa de Tapas',
    'Calle Mayor, 84, Madrid, Spain',
    'Madrid',
    'Spain',
    40.4168,
    -3.7038,
    false,
    'https://example.com/tapas-madrid',
    ARRAY['es', 'en'],
    ARRAY['/placeholder.svg?height=400&width=600'],
    'seed-user-005',
    'Tapas Wine Tasting food wine culture Spanish traditional Madrid Spain',
    'tapas wine tasting food wine culture spanish traditional madrid spain',
    'PUBLISHED',
    NOW(),
    NOW()
  ),
  -- Workshop events
  (
    'seed011',
    'Pottery Workshop for Beginners',
    'Learn traditional ceramic techniques in a hands-on 3-hour workshop.',
    ARRAY['workshop', 'art', 'craft'],
    NOW() + INTERVAL '8 days',
    NOW() + INTERVAL '8 days' + INTERVAL '3 hours',
    'Europe/Athens',
    'Keramikos Art Studio',
    'Keramikos, Athens, Greece',
    'Athens',
    'Greece',
    37.9778,
    23.7178,
    false,
    NULL,
    ARRAY['el', 'en'],
    ARRAY['/placeholder.svg?height=400&width=600'],
    'seed-user-006',
    'Pottery Workshop Beginners art craft ceramic traditional Athens Greece',
    'pottery workshop beginners art craft ceramic traditional athens greece',
    'PUBLISHED',
    NOW(),
    NOW()
  ),
  (
    'seed012',
    'Corso di Cucina Italiana',
    'Impara a preparare pasta fresca e tiramisù con uno chef professionista.',
    ARRAY['workshop', 'food', 'cooking'],
    NOW() + INTERVAL '12 days',
    NOW() + INTERVAL '12 days' + INTERVAL '4 hours',
    'Europe/Rome',
    'Cucina Bella',
    'Via dei Coronari, 44, Rome, Italy',
    'Rome',
    'Italy',
    41.9009,
    12.4702,
    false,
    'https://example.com/cucina-italiana',
    ARRAY['it', 'en'],
    ARRAY['/placeholder.svg?height=400&width=600'],
    'seed-user-006',
    'Corso di Cucina Italiana workshop food cooking pasta chef Rome Italy',
    'corso di cucina italiana workshop food cooking pasta chef rome italy',
    'PUBLISHED',
    NOW(),
    NOW()
  )
ON CONFLICT (id) DO NOTHING;

-- Create seed users
INSERT INTO "User" (id, email, name, "createdAt")
VALUES 
  ('seed-user-001', 'organizer1@eventa.test', 'Maria Papadopoulos', NOW()),
  ('seed-user-002', 'organizer2@eventa.test', 'Luca Rossi', NOW()),
  ('seed-user-003', 'organizer3@eventa.test', 'Carmen García', NOW()),
  ('seed-user-004', 'organizer4@eventa.test', 'Sophie Martin', NOW()),
  ('seed-user-005', 'organizer5@eventa.test', 'Andrew Miller', NOW()),
  ('seed-user-006', 'organizer6@eventa.test', 'Elena Dimitriou', NOW())
ON CONFLICT (id) DO NOTHING;
